name: Deploy to ALL-INKL via FTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Upload via FTP
        run: |
          lftp -e "
            set ftp:ssl-allow yes;
            set ftp:ssl-force no;
            set ftp:passive-mode yes;
            set ssl:verify-certificate no;
            set net:max-retries 3;
            set net:reconnect-interval-base 5;
            open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }};
            mirror --reverse --verbose --overwrite --exclude .git/ --exclude .github/ --exclude .DS_Store --exclude node_modules/ ./public_html/ /tokmak-gmbh.de/;
            quit
          "
